---
version: "3"

services:
  prom:
    image: prom/prometheus
    volumes:
      - ./monitor/prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "5000:3000"
    depends_on:
      - prom

  exporter:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - "prometheus_exporter"
    ports:
      - "9394:9394"

  rails:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - "rails"
      - "server"
      - "-b"
      - "0.0.0.0"
    ports:
      - "3000:3000"
    depends_on:
      - exporter

  generator:
    build:
      context: ./contrib/generator
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app/contrib/generator
    command:
      - bash
      - generator.sh
    depends_on:
      - rails

volumes:
  grafana-storage:
